# 텍스트 전처리

## 1. 토큰화(Tokenization)

## 1) 문장 토큰화

In [1]:
from nltk.tokenize import sent_tokenize

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
sent_tokenize(text)

['His barber kept his word.',
 'But keeping such a huge secret to himself was driving him crazy.',
 'Finally, the barber went up a mountain and almost to the edge of a cliff.',
 'He dug a hole in the midst of some reeds.',
 'He looked about, to make sure no one was near.']

In [4]:
text="I am actively looking for Ph.D. students. and you are a Ph.D student."
sent_tokenize(text)

# NLTK가 단순히 마침표를 기준으로 하지 않은 것을 알 수 있음

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']

In [5]:
!pip install kss
import kss

     |████████████████████████████████| 71kB 5.3MB/s eta 0:00:011


In [6]:
text='딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어려워요. 농담아니에요. 이제 해보면 알걸요?'
kss.split_sentences(text)

['딥 러닝 자연어 처리가 재미있기는 합니다.',
 '그런데 문제는 영어보다 한국어로 할 때 너무 어려워요.',
 '농담아니에요.',
 '이제 해보면 알걸요?']

### 2) 단어 토큰화

In [7]:
from nltk.tokenize import word_tokenize  
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))  

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [8]:
from nltk.tokenize import WordPunctTokenizer  
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))
# 토큰화 모듈에 따라 결과가 조금씩 다르다.

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [9]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [10]:
nltk.download('averaged_perceptron_tagger')
from nltk.tag import pos_tag

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [11]:
# 품사 태깅
x=word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop.")
pos_tag(x)

[('Do', 'VBP'),
 ("n't", 'RB'),
 ('be', 'VB'),
 ('fooled', 'VBN'),
 ('by', 'IN'),
 ('the', 'DT'),
 ('dark', 'NN'),
 ('sounding', 'VBG'),
 ('name', 'NN'),
 (',', ','),
 ('Mr.', 'NNP'),
 ('Jone', 'NNP'),
 ("'s", 'POS'),
 ('Orphanage', 'NN'),
 ('is', 'VBZ'),
 ('as', 'RB'),
 ('cheery', 'JJ'),
 ('as', 'IN'),
 ('cheery', 'NN'),
 ('goes', 'VBZ'),
 ('for', 'IN'),
 ('a', 'DT'),
 ('pastry', 'NN'),
 ('shop', 'NN'),
 ('.', '.')]

In [12]:
!pip install konlpy

     |████████████████████████████████| 19.4MB 1.3MB/s 
     |████████████████████████████████| 460kB 46.1MB/s 
     |████████████████████████████████| 92kB 12.2MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [13]:
from konlpy.tag import Okt  
okt=Okt()  
text= "열심히 코딩한 당신, 연휴에는 여행을 가봐요"
print(okt.morphs(text))
print(okt.nouns(text))  

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
['코딩', '당신', '연휴', '여행']


In [15]:
from konlpy.tag import Kkma  
kkma=Kkma() 
text= "열심히 코딩한 당신, 연휴에는 여행을 가봐요"
print(kkma.morphs(text))
print(kkma.pos(text))  
print(kkma.nouns(text))  

['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
[('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]
['코딩', '당신', '연휴', '여행']


## 2. 정규화

### 1) 대/소문자 통합

In [16]:
def lowertext(text):
    return text.lower()

text = "Do Not Go Gentle Into That Good Night"
lowertext(text)

'do not go gentle into that good night'

### 2) 불필요한 단어의 제거
- 등장 빈도가 적은 단어
- 길이가 짧은 단어

In [17]:
# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
import re
text = "I was wondering if anyone out there could enlighten me on this car."
shortword = re.compile(r'\W*\b\w{1,2}\b') # \b: 경계(boundary)
print(shortword.sub('', text))

 was wondering anyone out there could enlighten this car.


### 3) 표제어 추출(Lemmatization)

In [18]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [19]:
from nltk.stem import WordNetLemmatizer
n=WordNetLemmatizer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([n.lemmatize(w) for w in words])

['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


In [20]:
print(n.lemmatize('dies', 'v'))
print(n.lemmatize('watched', 'v'))
print(n.lemmatize('watched', 'v'))
print(n.lemmatize('flies', 'n'))
print(n.lemmatize('flies', 'v'))

die
watch
watch
fly
fly


### 4) 어간 추출(Stemming)

In [21]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

s = PorterStemmer()
text="This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
words=word_tokenize(text)
print(words)

['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']


In [22]:
print([s.stem(w) for w in words])

['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


In [23]:
words=['formalize', 'allowance', 'electricical']
print([s.stem(w) for w in words])

['formal', 'allow', 'electric']


In [24]:
from nltk.stem import PorterStemmer
s=PorterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([s.stem(w) for w in words])

['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']


In [25]:
from nltk.stem import LancasterStemmer
l=LancasterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([l.stem(w) for w in words])

['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


### 5) [정규표현식](#cell-id)

## 3. 정제

### 1) 맞춤법 검사

In [26]:
!pip install git+https://github.com/ssut/py-hanspell.git
from hanspell import spell_checker

  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-m91a9u7u
  Running command git clone -q https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-m91a9u7u
  Created wheel for py-hanspell: filename=py_hanspell-1.1-cp37-none-any.whl size=4854 sha256=27e6aa19ca54f73ec60dd8d6c2c5b97e2f78730c8357d688e8e87f7a78ab5299
  Stored in directory: /tmp/pip-ephem-wheel-cache-i349it6l/wheels/0a/25/d1/e5e96476dbb1c318cc26c992dd493394fe42b0c204b3e65588
Successfully built py-hanspell


In [27]:
sent = "맞춤법 틀리면 외 않되? 쓰고싶은대로쓰면돼지 "
spelled_sent = spell_checker.check(sent)

hanspell_sent = spelled_sent.checked
print(hanspell_sent)

맞춤법 틀리면 왜 안돼? 쓰고 싶은 대로 쓰면 되지


### 2) 불용어 처리

In [28]:
nltk.download('stopwords')

from nltk.corpus import stopwords  
stopwords.words('english')[:10]  

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [29]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_tokens = word_tokenize(example)

result = []
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 

print(word_tokens) 
print(result) 

['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [30]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."

# 불용어 입력
stop_words = "아무거나 아무렇게나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 하면 아니거든"

stop_words=stop_words.split(' ')
word_tokens = word_tokenize(example)

result = [] 
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 

# result=[word for word in word_tokens if not word in stop_words]

print(word_tokens) 
print(result)

['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']


## 4. 인코딩

### 1) 정수 인코딩

In [31]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [32]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

text = sent_tokenize(text)
print(text)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [33]:
# 정제와 단어 토큰화
vocab = {} # 파이썬의 dictionary 자료형
sentences = []
stop_words = set(stopwords.words('english'))

for i in text:
    sentence = word_tokenize(i) # 단어 토큰화를 수행합니다.
    result = []

    for word in sentence: 
        word = word.lower() # 모든 단어를 소문자화하여 단어의 개수를 줄입니다.
        if word not in stop_words: # 단어 토큰화 된 결과에 대해서 불용어를 제거합니다.
            if len(word) > 2: # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거합니다.
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0 
                vocab[word] += 1
    sentences.append(result) 
print(sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [34]:
print(vocab)
print(vocab["barber"])

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}
8


In [35]:
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [36]:
word_to_index = {}
i=0
for (word, frequency) in vocab_sorted :
    if frequency > 1 : # 정제(Cleaning) 챕터에서 언급했듯이 빈도수가 적은 단어는 제외한다.
        i=i+1
        word_to_index[word] = i
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [37]:
vocab_size = 5
words_frequency = [w for w,c in word_to_index.items() if c >= vocab_size + 1] # 인덱스가 5 초과인 단어 제거
for w in words_frequency:
    del word_to_index[w] # 해당 단어에 대한 인덱스 정보를 삭제
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [38]:
# Out-Of-Vocabulary(단어 집합에 없는 단어)
word_to_index['OOV'] = len(word_to_index) + 1

In [39]:
encoded = []
for s in sentences:
    temp = []
    for w in s:
        try:
            temp.append(word_to_index[w])
        except KeyError:
            temp.append(word_to_index['OOV'])
    encoded.append(temp)
print(encoded)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [40]:
# collections 패키지를 이용한 방법
from collections import Counter

# flatten
words = sum(sentences, [])


vocab = Counter(words) # 파이썬의 Counter 모듈을 이용하면 단어의 모든 빈도를 쉽게 계산할 수 있습니다.
print(vocab)


vocab_size = 5
vocab = vocab.most_common(vocab_size) # 등장 빈도수가 높은 상위 5개의 단어만 저장

word_to_index = {}
i = 0
for (word, frequency) in vocab :
    i = i+1
    word_to_index[word] = i
print(word_to_index)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


### 2) 패딩

In [41]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [42]:
sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [43]:
# 정수 인코딩
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences) # fit_on_texts()안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성한다.

encoded = tokenizer.texts_to_sequences(sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [44]:
# 최대 길이 계산
max_len = max(len(item) for item in encoded)
print(max_len)

7


In [45]:
for item in encoded: # 각 문장에 대해서
    while len(item) < max_len:   # max_len보다 작으면
        item.append(0) # 패딩

padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [46]:
# 케라스를 이용한 방법
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(sentences)
print(encoded)

padded = pad_sequences(encoded, padding = 'post', maxlen = 5)
padded


[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

### 3) 원-핫 인코딩

In [47]:
from konlpy.tag import Okt  
okt=Okt()  
token=okt.morphs("나는 자연어 처리를 배운다")  
print(token)

['나', '는', '자연어', '처리', '를', '배운다']


In [48]:
word2index={}
for voca in token:
     if voca not in word2index.keys():
       word2index[voca]=len(word2index)
print(word2index)

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [49]:
def one_hot_encoding(word, word2index):
       one_hot_vector = [0]*(len(word2index))
       index=word2index[word]
       one_hot_vector[index]=1
       return one_hot_vector

In [50]:
one_hot_encoding("자연어",word2index)

[0, 0, 1, 0, 0, 0]

In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text="나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

t = Tokenizer()
t.fit_on_texts([text])
print(t.word_index) # 각 단어에 대한 인코딩 결과 출력.

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [52]:
sub_text="점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded=t.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 5, 1, 6, 3, 7]


In [53]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


-------------------------
<a name="cell-id"></a>
## +)정규표현식(Regular Expression)
- https://regexr.com/
 
주요 함수
- re.search: 패턴이 일치하는 첫번째 문자열만 반환 (결과값은 1개) 
- re.match: 주어진 문자열의 첫글자부터 일치하는 패턴 문자열을 반환 (결과값은 1개)
- re.findall: 패턴이 일치하는 문자열을 **모두** 찾아서 반환한다.
- re.sub: 특정 패턴을 찾아서 다른 문자열로 변경
- re.compile: 패턴을 **반복**적으로 적용하는 경우 효율적이다.
```
# compile 사용
객체 = re.compile('패턴')
객체.match('문자열1')
객체.match('문자열2')
객체.match('문자열3')
.
# compile 사용x
re.match(패턴, '문자열1')
re.match(패턴, '문자열2')
re.match(패턴, '문자열3')
```


In [54]:
input_text_1 = "계절이 지나가는 하늘에는 가을로 가득차 있습니다."
input_text_2 = "나는 아무 걱정도 없이 가을 속의 별들을 다 헤일 듯 합니다."
input_text_3 = "별 하나에 추억과"

p = re.compile('니다.$')

print(p.search(input_text_1))
print(p.search(input_text_2))
print(p.search(input_text_3))

<re.Match object; span=(24, 27), match='니다.'>
<re.Match object; span=(31, 34), match='니다.'>
None


### 1. 특정 패턴 찾기
- 1개 문자열 찾기

#### 1) 숫자: \d

In [55]:
import re

In [ ]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\d"
print(re.findall(regex, input_text))

['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']


#### 2) 숫자가 아닌 모든 문자열: \D

In [56]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\D"
print(re.findall(regex, input_text))

['e', 'n', 'g', 'l', 'i', 's', 'h', '\t', '한', '글', ' ', '漢', '字', ' ', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')']


#### 3) 띄어쓰기, 탭, 줄바꿈 등의 공백문자: \s

In [57]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\s"
print(re.findall(regex, input_text))

['\t', ' ', ' ']


#### 4) 공백문자가 아닌 모든 문자열: \S

In [58]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\S" 
print(re.findall(regex, input_text))

['e', 'n', 'g', 'l', 'i', 's', 'h', '한', '글', '漢', '字', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')']


#### 5) # 문자 또는 숫자: \w

In [59]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\w" 
print(re.findall(regex, input_text))

['e', 'n', 'g', 'l', 'i', 's', 'h', '한', '글', '漢', '字', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']


#### 6) 문자 또는 숫자가 아닌 모든 문자열: \W

In [60]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "\W" 
print(re.findall(regex, input_text))

['\t', ' ', ' ', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')']


#### 7) 줄바꿈을 제외한 모든 문자열: .

In [61]:
input_text = "english\t한글 漢字 1234567890!@#$%^&*()"
regex = "." 
print(re.findall(regex, input_text))

['e', 'n', 'g', 'l', 'i', 's', 'h', '\t', '한', '글', ' ', '漢', '字', ' ', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')']


### 2. 특정 패턴 찾기-2
- 여러개로 이루어진 문자열 찾기

#### 0) 앞/뒤 문자열로 판단하기
- 맨 앞에 특정 문자열이 오는 경우: ^문자열
- 맨 뒤에 특정 문자열이 오는 경우: 문자열$

In [62]:
input_text = "중요한 메일 놓치지 않기. 내가 메일을 놓치지 않고 처리할 수 있도록 후속 조치를 하고 답장을 보내라고 Gmail에서 알려줍니다."
regex = "^중요한"
print(bool(re.search(regex, input_text)))

True


In [63]:
input_text = "중요한 메일 놓치지 않기. 내가 메일을 놓치지 않고 처리할 수 있도록 후속 조치를 하고 답장을 보내라고 Gmail에서 알려줍니다."
regex = "^안녕하세요"
print(bool(re.search(regex, input_text)))

False


In [64]:
input_text = "중요한 메일 놓치지 않기. 내가 메일을 놓치지 않고 처리할 수 있도록 후속 조치를 하고 답장을 보내라고 Gmail에서 알려줍니다."
regex = "알려줍니다.$"
print(bool(re.search(regex, input_text)))

True


#### 1) Zero or many: *

In [65]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "\w*번호"
print(re.findall(regex, input_text))

['전화번호', '지역번호', '번호']


#### 2) One or many: + 

In [66]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "\w+번호"
print(re.findall(regex, input_text))

['전화번호', '지역번호']


#### 3) zero or one: ?

In [67]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "Phon\w?"
print(re.findall(regex, input_text))

['Phone']


#### 4) 패턴 반복
- {n}: 앞 패턴이 n번 반복
- {n,m}:앞 패턴이 n~m번 반복


In [68]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "\d{4}"
print(re.findall(regex, input_text))

['5678']


In [69]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "\d{2,4}"
print(re.findall(regex, input_text))

['02', '123', '5678']


#### 5) 범위 지정
- []: 지정한 범위 내에서 1개 문자열
- -: 범위를 나타낼 때 사용. []와 함께 사용됨. 
- |: or
- ^: ~이외의
   
** 1에서 정리한 패턴들은 범위 지정을 통해 나타낼 수도 있습니다.
<img src="https://t1.daumcdn.net/cfile/tistory/99D7D73A5AC895F31A?download">

In [70]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[a-z]+"
print(re.findall(regex, input_text))

['hone', 'umber']


In [71]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[A-Z]+"
print(re.findall(regex, input_text))

['P', 'N']


In [72]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[a-zA-Z]+"
print(re.findall(regex, input_text))

['Phone', 'Number']


In [73]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[가-힣]+"
print(re.findall(regex, input_text))

['전화번호', '는', '처럼', '지역번호', '자리', '자리', '번호패턴을', '가집니다']


In [74]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[0-9|a-zA-Z]+"
print(re.findall(regex, input_text))

['Phone', 'Number', '02', '123', '5678', '3', '4', '4']


In [75]:
input_text = "전화번호(Phone Number)는 02-123-5678 처럼 \"지역번호-3~4자리-4자리\" 번호패턴을 가집니다."
regex = "[^0-9]+"
print(re.findall(regex, input_text))

['전화번호(Phone Number)는 ', '-', '-', ' 처럼 "지역번호-', '~', '자리-', '자리" 번호패턴을 가집니다.']


### 3. 다른 문자열로 대체하기

In [ ]:
input_text = "[2019-08-01 공지] SNS에 자신의 전화번호를 '내전번 010-1234-5678 통화ㄱㄱ'과 같이 댓글로 남기는 것은 매우 위험합니다."
regex = "\d{4}"
result = re.sub(regex, 'XXXX', input_text)
print(result)

[XXXX-08-01 공지] SNS에 자신의 전화번호를 '내전번 010-XXXX-XXXX 통화ㄱㄱ'과 같이 댓글로 남기는 것은 매우 위험합니다.


In [76]:
result = re.sub('(\d{4})-(\d{4})', '****-****', input_text)
print(result)

전화번호(Phone Number)는 02-123-5678 처럼 "지역번호-3~4자리-4자리" 번호패턴을 가집니다.


### 4. 퀴즈

#### 1) 이메일 주소 검사하기
- 이메일 형식
```
계정@도메인.최상위도메인
```

In [ ]:
emails = ['python@mail.example.com', 'python+kr@example.com',              # 올바른 형식
          'python-dojang@example.co.kr', 'python_10@example.info',         # 올바른 형식
          'python.dojang@e-xample.com',                                    # 올바른 형식
          '@example.com', 'python@example', 'python@example-com']          # 잘못된 형식 

In [ ]:
p = re.compile(#####) # 이곳을 채워주세요!

In [ ]:
for i in emails:
  print(bool(p.search(i))) # 순서대로 True 5개 , False 3개개

True
True
True
True
True
False
False
False


<details>
    <summary>Solution</summary>
    <div>
        '^\S+@\S+\.\S+$'
    </div>
</details>

#### 2) URL 검사하기
- URL 형식
```
http:// 또는 https://로 시작
도메인은 도메인.최상위도메인 형식이며 영문 대소문자, 숫자, -로 되어 있어야 함
도메인 이하 경로는 /로 구분하고, 영문 대소문자, 숫자, -, _, ., ?, =을 사용함
```

In [ ]:
def check_url(url):
  p = re.compile(#####) # 이곳을 채워주세요!
  return bool(p.search(url))

In [ ]:
url = 'http://www.example.com/hello/world.do?key=python'
check_url(url) # True

True

In [ ]:
url = 'https://example/hello/world.html'
check_url(url) # False

False

<details>
    <summary>Solution</summary>
    <div>
        '(^http://|https://)[a-zA-Z0-9-]+\.[a-zA-Z0-9-]+\/*[a-zA-Z0-9-_.?=]*'
    </div>
</details>